package com.tale.model.po.mbg;

public class TAttach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.fname
     * 附件名称
     *
     * @mbggenerated
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.ftype
     * 附件类型
     *
     * @mbggenerated
     */
    private String ftype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.fkey
     * 关键字
     *
     * @mbggenerated
     */
    private String fkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.author_id
     * 作者ID
     *
     * @mbggenerated
     */
    private Integer author_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_attach.created
     * 创建次数
     *
     * @mbggenerated
     */
    private Integer created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.id
     *
     * @return the value of t_attach.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.id
     *
     * @param id the value for t_attach.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.fname
     *
     * @return the value of t_attach.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.fname
     *
     * @param fname the value for t_attach.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.ftype
     *
     * @return the value of t_attach.ftype
     *
     * @mbggenerated
     */
    public String getFtype() {
        return ftype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.ftype
     *
     * @param ftype the value for t_attach.ftype
     *
     * @mbggenerated
     */
    public void setFtype(String ftype) {
        this.ftype = ftype == null ? null : ftype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.fkey
     *
     * @return the value of t_attach.fkey
     *
     * @mbggenerated
     */
    public String getFkey() {
        return fkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.fkey
     *
     * @param fkey the value for t_attach.fkey
     *
     * @mbggenerated
     */
    public void setFkey(String fkey) {
        this.fkey = fkey == null ? null : fkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.author_id
     *
     * @return the value of t_attach.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthor_id() {
        return author_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.author_id
     *
     * @param author_id the value for t_attach.author_id
     *
     * @mbggenerated
     */
    public void setAuthor_id(Integer author_id) {
        this.author_id = author_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_attach.created
     *
     * @return the value of t_attach.created
     *
     * @mbggenerated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_attach.created
     *
     * @param created the value for t_attach.created
     *
     * @mbggenerated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fname=").append(fname);
        sb.append(", ftype=").append(ftype);
        sb.append(", fkey=").append(fkey);
        sb.append(", author_id=").append(author_id);
        sb.append(", created=").append(created);
        sb.append("]");
        return sb.toString();
    }
}