package com.tale.mybatis.dao.write.mbg;

import com.tale.model.po.mbg.TAttach;
import com.tale.model.po.mbg.TAttachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBGTAttachWriteDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int countByExample(TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int deleteByExample(TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int insert(TAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int insertSelective(TAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    List<TAttach> selectByExample(TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    TAttach selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TAttach record, @Param("example") TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TAttach record, @Param("example") TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TAttach record);
}