package com.tale.mybatis.dao.read.mbg;

import com.tale.model.po.mbg.TAttach;
import com.tale.model.po.mbg.TAttachExample;
import java.util.List;

public interface MBGTAttachReadDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    int countByExample(TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    List<TAttach> selectByExample(TAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_attach
     *
     * @mbggenerated
     */
    TAttach selectByPrimaryKey(Integer id);
}